name: CI Release


    
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Build number'
        required: true
        default: 'vX.Y.Z'

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'master' }}
    permissions:
      contents: write
    steps:
    - name: Archive
      uses: 'actions/checkout@master'
      with:
        submodules: recursive
    
    - name: Archive
      uses: 'thedoctor0/zip-release@0.7.1'
      with:
        type: 'zip'
        filename: 'Western.Goods.${{ env.INPUT_TAG_NAME }}.zip'
        exclusions: '*.git*'
    
    - name: Release
      uses: 'marvinpinto/action-automatic-releases@v1.2.1'
      with:
        files: 'Western.Goods.${{ env.INPUT_TAG_NAME }}.zip'
        title: 'Western Goods ${{ env.INPUT_TAG_NAME }}'
        automatic_release_tag: '${{ env.INPUT_TAG_NAME }}'
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
