name: CI Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'develop' }} #replace with master
    permissions:
      contents: write
    steps:
    - name: Archive
      uses: 'actions/checkout@master'
      with:
        submodules: recursive
    
    - name: Archive
      uses: 'thedoctor0/zip-release@0.7.1'
      with:
        type: 'zip'
        filename: 'Western.Goods.${{ github.ref_name }}.zip'
        exclusions: '*.git*'
    
    - name: Release
      uses: 'marvinpinto/action-automatic-releases@v1.2.1'
      with:
        files: 'Western.Goods.${{ github.ref_name }}.zip'
        title: 'Western Goods ${{ github.ref_name }}'
        automatic_release_tag: '${{ github.ref_name }}'
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
