name: CI Release

on:
  workflow_dispatch:
    inputs:
      build-ver:
        description: 'Build version'
        required: true
        default: 'v0.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'master' }}
    permissions:
      contents: write
    steps:
    - name: Checkout
      id: checkout
      uses: 'actions/checkout@master'
      with:
        submodules: recursive

    - name: Archive
      id: archive
      uses: 'thedoctor0/zip-release@0.7.1'
      with:
        type: 'zip'
        filename: 'Western.Goods.${{ github.event.inputs.build-ver }}.zip'
        exclusions: '*.git*'

    - name: Changelog
      id: changelog
      run: 'echo ${{ github.event.head_commit.message }} > changelog.md'
      
    # - name: Release
    #   id: release
    #   uses: 'ncipollo/release-action@v1.13.0'
    #   env: 
    #     GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    #   with: 
    #     tag: '${{ github.event.inputs.build-ver }}'
    #     name: 'Western Goods ${{ github.event.inputs.build-ver }}'
    #     body: '${{ github.event.head_commit.message }}'
    #     artifacts: 'Western.Goods.${{ github.event.inputs.build-ver }}.zip'
    #     prerelease: false
    
    - name: Release
      id: release
      uses: 'softprops/action-gh-release@v0.1.15'
      env: 
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      with: 
        tag_name: '${{ github.event.inputs.build-ver }}'
        name: 'Western Goods ${{ github.event.inputs.build-ver }}'
        body: |
          - test **markdown** [link](https://www.google.com)
          ${{ github.event.head_commit.message }}
        artifacts: 'Western.Goods.${{ github.event.inputs.build-ver }}.zip'
        prerelease: false
    
    # - name: Release
    #   id: release
    #   uses: 'actions/create-release@latest'
    #   env: 
    #     GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    #   with: 
    #     tag_name: '${{ github.event.inputs.build-ver }}'
    #     release_name: 'Western Goods ${{ github.event.inputs.build-ver }}'
    #     body_path : './changelog.md'
    #       # ${{ github.event.head_commit.message }}
    #     prerelease: false

    # - name: Upload Archive
    #   id: upload-archive 
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.release.outputs.upload_url }}
    #     asset_path: './Western.Goods.${{ github.event.inputs.build-ver }}.zip'
    #     asset_name: 'Western.Goods.${{ github.event.inputs.build-ver }}.zip'
    #     asset_content_type: application/zip
