name: CI Release


    
on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'Build number'
        required: true
        default: 'vX.Y.Z'

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'master' }}
    permissions:
      contents: write
    steps:
    - name: Archive
      uses: 'actions/checkout@master'
      with:
        submodules: recursive
    
    - name: Archive
      uses: 'thedoctor0/zip-release@0.7.1'
      with:
        type: 'zip'
        filename: 'Western.Goods.${{ github.event.inputs.tag-name }}.zip'
        exclusions: '*.git*'
    
    - name: Release
      uses: 'marvinpinto/action-automatic-releases@v1.2.1'
      with:
        files: 'Western.Goods.${{ github.event.inputs.tag-name }}.zip'
        title: 'Western Goods ${{ github.event.inputs.tag-name }}'
        automatic_release_tag: '${{ github.event.inputs.tag-name }}'
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
